name: Deploy in main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Supprimez la stratégie "matrix" inutile ici
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3 # Passez à la v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Install Wrangler globally (avec Node.js 20)
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages project create chinafrica --production-branch=main || true
          npx wrangler pages deploy dist --project-name=chinafrica
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_DEPLOY_TO_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
#EAyKoVpCieYurjQGCZHfC5hy3rbWrEcefusvQScS
